# Generated by Django 4.2.7 on 2023-12-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
