# Generated by Django 4.2.7 on 2024-01-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
