# Generated by Django 4.2.7 on 2023-12-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='car',
            new_name='post',
        ),
    ]
