# Generated by Django 4.2.7 on 2023-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boolean_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_field',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
