# Generated by Django 4.2.7 on 2023-12-05 09:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_boolean_field_student_date_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datetime_field',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_field',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='student',
            name='email_field',
            field=models.EmailField(default='niloy@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='float_field',
            field=models.FloatField(default=23.9),
        ),
        migrations.AddField(
            model_name='student',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='student',
            name='null_boolean_field',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='url_field',
            field=models.URLField(default='https://example.com'),
        ),
    ]
